const sig = (label, type) => {
  const m = { intent: { bg: "#FAEEDA", color: "#854F0B" }, content: { bg: "#E6F1FB", color: "#185FA5" }, growth: { bg: "#E1F5EE", color: "#0F6E56" }, tech: { bg: "#EEEDFE", color: "#534AB7" }, risk: { bg: "#FCEBEB", color: "#A32D2D" }, momentum: { bg: "#E1F5EE", color: "#0F6E56" }, stakeholder: { bg: "#E6F1FB", color: "#185FA5" }, timing: { bg: "#FAEEDA", color: "#854F0B" }, competitive: { bg: "#EEEDFE", color: "#534AB7" }, coaching: { bg: "#FFF0E6", color: "#9C4D1A" } };
  return { label, ...(m[type] || m.intent) };
};

export const COMPANY_NAME = "Rely Home";
export const COMPANY_LOGO_LETTER = "R";
export const ROLE_LABEL = "Sales Manager";
export const REP = { name: "Jessica Thornton", initials: "JT" };

export const TABS = ["Hot prospects", "Real estate partners", "Follow-ups", "Team coaching"];

export const ALL_LEADS = {
  "Hot prospects": [
    { id: 1, name: "Rachel Mendez", company: "Compass Real Estate - Austin", role: "Managing Broker", stage: "Demo Scheduled", size: "$185K", score: 96, signals: [sig("Requested pricing for 45 agents", "intent"), sig("Current vendor contract expires April 15", "timing"), sig("Viewed case study 3x this week", "content")], message: "Rachel's office closes 1,200+ transactions annually. She's actively shopping warranty providers before current contract lapses in 2 weeks. Demo is Thursday at 2pm CT.", priority: "high" },
    { id: 2, name: "Tom Bridwell", company: "Meritage Homes - DFW Division", role: "Sales Director", stage: "Proposal Sent", size: "$240K", score: 94, signals: [sig("1,800 units projected this year", "growth"), sig("Builder warranty bundling approved", "intent"), sig("VP forwarded proposal to legal", "stakeholder")], message: "Meritage DFW division wants warranty in every new construction close. Tom confirmed his VP forwarded our proposal to legal -- expect redlines by Wednesday.", priority: "high" },
    { id: 3, name: "Karen Liu", company: "Realty ONE Group - Phoenix", role: "Franchise Owner", stage: "Negotiation", size: "$165K", score: 93, signals: [sig("92 agents across 2 offices", "growth"), sig("Agent incentive program interest", "intent"), sig("Displaced competitor last month", "competitive")], message: "Karen dropped American Home Shield after claim resolution complaints. She wants agent commission on every warranty sold -- negotiating revenue share terms.", priority: "high" },
    { id: 4, name: "David Park", company: "Guild Mortgage - Southeast", role: "Regional Sales Manager", stage: "Demo Scheduled", size: "$130K", score: 91, signals: [sig("Closing gift program rollout", "intent"), sig("480 loan officers in region", "growth"), sig("VP mortgage approved pilot", "stakeholder")], message: "Guild Mortgage SE region piloting warranty as closing gift. David's team of 480 LOs could drive significant volume if pilot succeeds. Demo Friday.", priority: "high" },
    { id: 5, name: "Stephanie Ruiz", company: "Taylor Morrison - Houston", role: "VP Sales & Marketing", stage: "Proposal Sent", size: "$210K", score: 89, signals: [sig("2,100 closings projected", "growth"), sig("Premium warranty tier request", "intent"), sig("Competitor pricing comparison", "competitive")], message: "Taylor Morrison Houston wants premium tier for homes over $500K. Stephanie comparing our pricing to First American -- need to sharpen proposal by Thursday.", priority: "high" },
    { id: 6, name: "Brian Walsh", company: "RE/MAX Elite - Denver", role: "Office Manager", stage: "Discovery", size: "$95K", score: 85, signals: [sig("68 agents, $380M volume", "growth"), sig("Attended our webinar Tuesday", "content"), sig("Asked about API integration", "tech")], message: "Brian attended our agent tools webinar and immediately asked about CRM integration. His office does $380M in volume -- high-value target for Colorado expansion.", priority: "medium" },
    { id: 7, name: "Maria Santos", company: "Greystar Property Management", role: "Director of Operations", stage: "Qualification", size: "$175K", score: 87, signals: [sig("12,000 units under management", "growth"), sig("Landlord warranty product inquiry", "intent"), sig("Budget approved for Q2", "timing")], message: "Greystar managing 12K rental units in Southeast. Interested in landlord warranty product for property owners. Budget allocated for Q2 vendor selection.", priority: "high" },
    { id: 8, name: "Chris Donovan", company: "Coldwell Banker - Chicago", role: "Branch Manager", stage: "Demo Scheduled", size: "$145K", score: 88, signals: [sig("110 agents in top-producing office", "growth"), sig("Agent adoption program interest", "intent"), sig("Previous Choice HW customer", "momentum")], message: "Chris's office was a Choice Home Warranty customer 3 years ago. Wants to re-engage with better agent tools. Demo set for Monday -- high win probability.", priority: "high" },
    { id: 9, name: "Amanda Foster", company: "NVR Inc. (Ryan Homes) - Mid-Atlantic", role: "Warranty Services Manager", stage: "Discovery", size: "$280K", score: 84, signals: [sig("15K homes delivered annually", "growth"), sig("Extended warranty add-on interest", "intent"), sig("National builder procurement process", "stakeholder")], message: "Ryan Homes exploring extended warranty beyond structural for Mid-Atlantic division. If successful, could expand to all NVR brands nationally.", priority: "medium" }
  ],
  "Real estate partners": [
    { id: 10, name: "Jennifer Hawkins", company: "Keller Williams - Lakewood", role: "Team Leader", stage: "Active Partner", size: "$125K/yr", score: 92, signals: [sig("Warranty attachment rate 34%", "momentum"), sig("Agent count grew 12% QoQ", "growth"), sig("Requesting co-marketing materials", "content")], message: "Jennifer's office is our #2 producing partner. Attachment rate climbing steadily. She wants co-branded flyers and open house materials for spring market.", priority: "high" },
    { id: 11, name: "Marcus Johnson", company: "eXp Realty - National Team", role: "Mega Team Lead", stage: "Active Partner", size: "$95K/yr", score: 88, signals: [sig("210-agent virtual team", "growth"), sig("Created warranty training video", "content"), sig("Revenue share model advocate", "momentum")], message: "Marcus's mega team is fully virtual across 14 states. He created his own warranty training video for agents. Wants exclusive revenue share tier for top producers.", priority: "medium" },
    { id: 12, name: "Priya Patel", company: "Century 21 - Bay Area", role: "Managing Broker", stage: "Active Partner", size: "$110K/yr", score: 85, signals: [sig("Attachment rate dropped to 18%", "risk"), sig("Agent turnover Q1", "risk"), sig("Requesting refresher training", "coaching")], message: "Priya's attachment rate dropped from 28% to 18% after agent turnover in Q1. Needs refresher training session for 15 new agents. Schedule ASAP to stop the slide.", priority: "high" },
    { id: 13, name: "Tyler Richardson", company: "Berkshire Hathaway HS - Carolinas", role: "Sales Manager", stage: "Active Partner", size: "$88K/yr", score: 82, signals: [sig("Luxury market specialist", "stakeholder"), sig("Premium tier pilot participant", "intent"), sig("Client satisfaction 4.7/5", "momentum")], message: "Tyler's luxury-focused team piloting our premium warranty tier. Client satisfaction scores are strong. Wants to present results at regional BHHS conference.", priority: "medium" },
    { id: 14, name: "Lisa Chang", company: "Redfin - Portland", role: "Lead Agent", stage: "At Risk", size: "$72K/yr", score: 60, signals: [sig("Redfin reducing agent headcount", "risk"), sig("Transaction volume down 25%", "risk"), sig("Still personally advocating", "stakeholder")], message: "Lisa personally loves our product but Redfin Portland office is shrinking. Transaction volume down significantly. Need contingency plan for this revenue.", priority: "high" },
    { id: 15, name: "Robert Garcia", company: "HomeSmart - Las Vegas", role: "Franchise Owner", stage: "Active Partner", size: "$140K/yr", score: 90, signals: [sig("185 agents, flat-fee model", "growth"), sig("Highest attachment rate in network: 41%", "momentum"), sig("Wants exclusivity agreement", "intent")], message: "Robert's office has our highest attachment rate nationwide. Requesting exclusive partnership agreement with enhanced commission structure. Worth protecting.", priority: "high" },
    { id: 16, name: "Sarah Blackwell", company: "Sotheby's International - Miami", role: "Associate Broker", stage: "New Partner", size: "$68K/yr", score: 79, signals: [sig("Ultra-luxury $2M+ avg price", "growth"), sig("Onboarding in progress", "momentum"), sig("White-label premium interest", "intent")], message: "Sarah joined last month. Her ultra-luxury Miami clientele needs white-labeled premium warranty. Onboarding team should prioritize concierge-level setup.", priority: "medium" },
    { id: 17, name: "Derek Williams", company: "EXIT Realty - Atlanta", role: "Broker/Owner", stage: "Active Partner", size: "$82K/yr", score: 83, signals: [sig("Expanding to 3rd office", "growth"), sig("Agent recruiting tool use case", "intent"), sig("Consistent 27% attachment rate", "momentum")], message: "Derek using warranty program as agent recruiting differentiator. Opening 3rd Atlanta office and wants warranty onboarding in new agent welcome kit.", priority: "medium" }
  ],
  "Follow-ups": [
    { id: 18, name: "Nicole Tran", company: "Windermere Real Estate - Seattle", role: "Office Manager", stage: "Follow-up", size: "$105K", score: 74, signals: [sig("Demo completed 2 weeks ago", "timing"), sig("Requested references from builders", "intent"), sig("Decision by April 15", "timing")], message: "Nicole liked the demo but wants builder references before deciding. Send Lennar and PulteGroup case studies. She has a hard deadline of April 15 for vendor selection.", priority: "high" },
    { id: 19, name: "James Okafor", company: "Howard Hanna Real Estate - Pittsburgh", role: "VP Sales", stage: "Follow-up", size: "$155K", score: 71, signals: [sig("Internal review with legal", "stakeholder"), sig("Asked for compliance documentation", "intent"), sig("Franchise disclosure review", "timing")], message: "James sent our agreement to Howard Hanna legal 10 days ago. Follow up Wednesday to check review status. He needs franchise disclosure compliance docs.", priority: "medium" },
    { id: 20, name: "Patricia Olsen", company: "M/I Homes - Columbus", role: "Director Homeowner Care", stage: "Follow-up", size: "$195K", score: 77, signals: [sig("Pricing revision requested", "intent"), sig("Comparing 3 vendors", "competitive"), sig("6,800 homes annually", "growth")], message: "Patricia asked for revised pricing after comparing with two competitors. She wants tiered pricing based on home value. Revised proposal due by Friday.", priority: "high" },
    { id: 21, name: "Anthony Russo", company: "Weichert Realtors - NJ/NY", role: "Regional Director", stage: "Follow-up", size: "$130K", score: 69, signals: [sig("Pilot program proposal sent", "momentum"), sig("Agent feedback collection period", "timing"), sig("Decision committee meets April 10", "timing")], message: "Weichert running internal agent feedback survey on warranty vendors. Their decision committee meets April 10. Need to ensure our pilot agents submit positive feedback.", priority: "medium" },
    { id: 22, name: "Samantha Cruz", company: "Invitation Homes - Southeast", role: "Property Manager", stage: "Follow-up", size: "$220K", score: 80, signals: [sig("80,000+ rental homes nationally", "growth"), sig("Landlord warranty pilot interest", "intent"), sig("Procurement approval pending", "stakeholder")], message: "Invitation Homes interested in bulk landlord warranty for Southeast portfolio. Procurement needs ROI model showing cost savings vs. self-insuring. Send analysis by Tuesday.", priority: "high" },
    { id: 23, name: "Kevin Murphy", company: "Long & Foster Real Estate", role: "Branch Manager", stage: "Follow-up", size: "$88K", score: 66, signals: [sig("Went dark after proposal", "risk"), sig("Last contact 3 weeks ago", "timing"), sig("Was enthusiastic in demo", "momentum")], message: "Kevin was very engaged during demo but has gone dark since receiving proposal. Try reaching via LinkedIn or through his admin. May be on vacation or dealing with internal changes.", priority: "medium" },
    { id: 24, name: "Diana Morales", company: "KB Home - Southwest Division", role: "Sales Operations Manager", stage: "Follow-up", size: "$175K", score: 75, signals: [sig("National builder RFP process", "stakeholder"), sig("SW division championing us", "momentum"), sig("Corporate alignment needed", "timing")], message: "Diana's SW division loves our product but KB Home requires corporate-level vendor approval. She's presenting our case to national procurement next week. Send supporting data.", priority: "medium" },
    { id: 25, name: "Eric Johansson", company: "Baird & Warner - Chicago", role: "Technology Director", stage: "Follow-up", size: "$92K", score: 72, signals: [sig("API integration testing complete", "tech"), sig("User acceptance testing phase", "momentum"), sig("Go-live target May 1", "timing")], message: "Baird & Warner completed API testing. UAT phase with 10 pilot agents starts next week. Need to ensure smooth experience -- this office is a Chicago market reference account.", priority: "medium" }
  ],
  "Team coaching": [
    { id: 26, name: "Jake Simmons", company: "Rely Home - Southeast Territory", role: "Territory Sales Rep", stage: "Coaching", size: "$1.2M quota", score: 72, signals: [sig("62% quota attainment YTD", "risk"), sig("High activity, low conversion", "coaching"), sig("Needs closing skills development", "coaching")], message: "Jake is making 45+ calls/week but converting at only 8%. His discovery meetings are strong but he struggles in negotiation and closing. Recommend ride-along on next 3 demos.", priority: "high" },
    { id: 27, name: "Alicia Reeves", company: "Rely Home - Northeast Territory", role: "Senior Territory Rep", stage: "Top Performer", size: "$1.5M quota", score: 95, signals: [sig("118% quota attainment", "momentum"), sig("Highest attachment rate in team", "growth"), sig("Mentoring 2 junior reps", "coaching")], message: "Alicia is crushing it with 118% attainment. Her real estate partner management skills are elite. Leverage her as mentor and have her lead next team training on partner engagement.", priority: "low" },
    { id: 28, name: "Marcus Bell", company: "Rely Home - Midwest Territory", role: "Territory Sales Rep", stage: "Coaching", size: "$1.3M quota", score: 68, signals: [sig("Pipeline quantity strong, quality weak", "coaching"), sig("Average deal size 30% below team", "risk"), sig("Pursuing too many small accounts", "coaching")], message: "Marcus has 85 accounts in pipeline but average deal size is $8.2K vs. team average of $11.7K. Needs coaching on account prioritization and targeting larger brokerages.", priority: "high" },
    { id: 29, name: "Priya Desai", company: "Rely Home - West Territory", role: "Territory Sales Rep", stage: "Ramping", size: "$800K quota (ramp)", score: 78, signals: [sig("90-day ramp, day 65", "timing"), sig("Completed all certifications", "momentum"), sig("First deal closed last week", "growth")], message: "Priya closed her first deal -- Windermere Seattle office. She's tracking ahead of ramp plan. Strong product knowledge from insurance background. Pair with Alicia for partner visits.", priority: "medium" },
    { id: 30, name: "Ryan Kowalski", company: "Rely Home - Texas Territory", role: "Territory Sales Rep", stage: "Coaching", size: "$1.4M quota", score: 75, signals: [sig("Builder channel specialist", "stakeholder"), sig("82% quota but lumpy revenue", "coaching"), sig("Q1 back-loaded 70% in March", "risk")], message: "Ryan's builder deals are large but infrequent, creating revenue lumpiness. 70% of Q1 revenue came in March. Coach him on maintaining parallel deal tracks to smooth out quarters.", priority: "medium" },
    { id: 31, name: "Tasha Williams", company: "Rely Home - Southeast Territory", role: "Territory Sales Rep", stage: "Coaching", size: "$1.2M quota", score: 65, signals: [sig("CRM hygiene below standards", "risk"), sig("Pipeline data unreliable", "coaching"), sig("Strong in-person but weak admin", "coaching")], message: "Tasha's in-person meetings get great feedback but her CRM is a mess. Pipeline reviews are unreliable because deal stages and close dates aren't updated. Implement daily CRM check-in.", priority: "high" },
    { id: 32, name: "Daniel Kim", company: "Rely Home - Pacific NW Territory", role: "Senior Territory Rep", stage: "Top Performer", size: "$1.5M quota", score: 91, signals: [sig("105% attainment, consistent quarters", "momentum"), sig("Best CRM discipline on team", "growth"), sig("Ready for promotion discussion", "stakeholder")], message: "Daniel is consistent top performer with excellent process discipline. He's been hinting about career growth. Discuss promotion to Senior Sales Manager or risk losing him to competitors.", priority: "medium" },
    { id: 33, name: "Laura Fitzgerald", company: "Rely Home - Mid-Atlantic Territory", role: "Territory Sales Rep", stage: "Coaching", size: "$1.3M quota", score: 70, signals: [sig("Insurance channel pioneer", "momentum"), sig("New channel, unclear playbook", "coaching"), sig("Needs executive selling skills", "coaching")], message: "Laura is developing the insurance carrier channel -- exciting but uncharted territory. She needs executive-level selling coaching to engage VP+ stakeholders at carriers like State Farm.", priority: "medium" }
  ]
};

export const CHAT_RESPONSES = {
  top_prospects: "Top 5 prospects by score and deal size this week: (1) Rachel Mendez at Compass Austin -- $185K, demo Thursday, vendor contract expiring in 2 weeks. (2) Tom Bridwell at Meritage DFW -- $240K, proposal in legal review. (3) Karen Liu at Realty ONE Phoenix -- $165K, negotiating rev share after dropping competitor. (4) David Park at Guild Mortgage SE -- $130K, pilot approved, demo Friday. (5) Stephanie Ruiz at Taylor Morrison Houston -- $210K, needs sharpened pricing by Thursday. Total pipeline from top 5: $930K.",
  partner_pipeline: "Active partner base generating $785K/yr recurring. Top performers: Robert Garcia (HomeSmart LV) at 41% attachment rate, Jennifer Hawkins (KW Lakewood) at 34%. At-risk: Lisa Chang (Redfin Portland) down 25% on volume due to headcount cuts, Priya Patel (Century 21 Bay Area) dropped from 28% to 18% after agent turnover. Priority actions: (1) Schedule refresher training for Priya's new agents, (2) Develop contingency plan for Redfin revenue, (3) Lock in Robert's exclusivity request.",
  this_weeks_priorities: "This week's critical actions: MONDAY -- Chris Donovan demo (Coldwell Banker Chicago, $145K, returning customer). TUESDAY -- Send Invitation Homes ROI analysis to Samantha Cruz ($220K). WEDNESDAY -- Follow up with James Okafor on legal review (Howard Hanna, $155K). THURSDAY -- Rachel Mendez demo (Compass Austin, $185K, contract expiring). FRIDAY -- David Park demo (Guild Mortgage SE, $130K) + send revised proposal to Stephanie Ruiz (Taylor Morrison, $210K). Total at-play this week: $1.05M.",
  rep_performance: "Team quota attainment YTD: Alicia Reeves 118% (NE), Daniel Kim 105% (PNW), Ryan Kowalski 82% (TX), Priya Desai on ramp, Jake Simmons 62% (SE), Marcus Bell 58% (MW). Key coaching needs: Jake needs closing skills (ride-alongs scheduled), Marcus needs account prioritization (deal size 30% below avg), Tasha needs CRM discipline (pipeline data unreliable). Bright spot: Priya closed first deal ahead of ramp schedule. Promote Alicia to lead next team training."
};

export const WEEKLY_DATA = [
  { week: "W1", value: 142000 },
  { week: "W2", value: 168000 },
  { week: "W3", value: 155000 },
  { week: "W4", value: 189000 },
  { week: "W5", value: 171000 },
  { week: "W6", value: 205000 },
  { week: "W7", value: 178000 },
  { week: "W8", value: 215000 },
  { week: "W9", value: 192000 },
  { week: "W10", value: 228000 },
  { week: "W11", value: 201000 },
  { week: "W12", value: 245000 }
];

export const PIPELINE_DATA = [
  { stage: "Prospect", value: 3200000 },
  { stage: "Discovery", value: 2400000 },
  { stage: "Demo Scheduled", value: 1800000 },
  { stage: "Proposal Sent", value: 1200000 },
  { stage: "Negotiation", value: 680000 },
  { stage: "Closed Won", value: 420000 }
];

export const CHAT_SUGGESTIONS = ["Top prospects", "Partner pipeline", "This week's priorities", "Rep performance"];

export const FUNNEL_DATA = [
  { stage: "Leads Generated", value: 480 },
  { stage: "Qualified", value: 290 },
  { stage: "Demo Completed", value: 165 },
  { stage: "Proposal Sent", value: 98 },
  { stage: "Negotiation", value: 54 },
  { stage: "Closed Won", value: 32 }
];

export const TOP_TEMPLATES = [
  { id: 1, name: "Partner Onboarding Playbook", description: "Step-by-step guide for activating new real estate office partnerships including agent training schedule and co-marketing setup" },
  { id: 2, name: "Agent Attachment Rate Toolkit", description: "Best practices and talk tracks for helping agents present home warranty to buyers and sellers at every transaction" },
  { id: 3, name: "Builder Channel Proposal Template", description: "Customizable proposal for new construction builders including volume pricing tiers and warranty bundling options" },
  { id: 4, name: "Weekly Team Coaching Scorecard", description: "Rep performance tracker covering activity metrics, pipeline quality, attachment rates, and coaching action items" }
];
